# Generated by Django 5.0 on 2023-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0002_library"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="library",
            name="membership_details",
            field=models.TextField(max_length=200),
        ),
    ]
