# Generated by Django 5.0 on 2023-12-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0004_borrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="borrowing_dt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="borrow",
            name="return_dt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
